config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#index"

# creating model routes - note that user does not need show page
  resources :contacts
  resources :events
  resources :users, only: [:index, :edit, :create, :update, :destroy]

# creating nested routes for contact/:id/events & events/:id/contacts
  resources :contacts, only: [:index] do
    resources :events, only: [:index]
  end
  resources :events, only: [:index] do
    resources :contacts, only: [:index, :new, :create]
  end

# custom routes for login & logout
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

# custom routes for google auth
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/login')

# custom routes for newsletter and unsubscribers
  get '/newsletter', to: "contacts#newsletter"
  post '/newsletter', to: "contacts#newsletter_update"
  get '/unsubscribed', to: "contacts#unsubscribed"

# custom route for welcome night form
  get '/welcome', to: "contacts#welcome"
  post '/welcome', to: "contacts#welcome_create"

  get '/international_connect', to: "contacts#international_connect"
  post '/international_connect', to: "contacts#international_connect_create"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  validates :email, presence: true
  validates :email, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :email, uniqueness: { message: "already taken. Try logging in with Google?" } 
  validates :password, format: { with: /\A(?=.*\d).{6,}\z/,
    message: "must be > 6 characters long & include > 1 number" }, allow_nil: true

  has_secure_password

  scope :same_level, -> (admin_level) { where('admin_level = ?', admin_level) }

  def name
    self.email[/[^@]*/]
  end

# compares user-provided code to secret ENV code and sets admin level appropriately
  def admin_level=(code)
    if code == ENV['ADMIN']
      self[:admin_level] = 2
    elsif code == ENV['IGSM']
      self[:admin_level] = 1
    else
      self[:admin_level] = 0
    end
  end

  def admin_level
    self[:admin_level]
  end

# creates a user from omniauth, setting credentials appropriately
  def self.from_omniauth(auth)
    @user = User.where(email: auth.info.email).first_or_initialize
    @user.admin_level=(ENV['IGSM']) if @user.email.include?("@gpmail.org")
    @user.password = SecureRandom.hex
    @user.save
    @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action only: [:index, :edit, :update, :destroy] do redirect_if_not_access(2) end
  before_action :redirect_if_logged_in, only: [:new, :create]
  before_action :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(email: user_params[:email], password: user_params[:password])
    @user.admin_level=(user_params[:admin_level])
    if @user.save
      session[:user_id] = @user.id
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    enter_code
    redirect_to users_path
  end

  def destroy
    @user.delete
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :admin_level)
  end

# takes admin's input (0, 1, or 2) & converts it to secret code for admin_level=(code) method
  def enter_code
    code = user_params[:admin_level].to_i
    if code == 2
      @user.admin_level=(ENV['ADMIN'])
    elsif code == 1
      @user.admin_level=(ENV['IGSM'])
    else
      @user.admin_level=(0)
    end
      @user.save
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Edit User Account Access", :description => "Remember that 0 is the lowest access, and 2 is the maximum access."} do %>

  <h2> Edit Access for <%= "#{@user.name.titleize}" %> </h2>

  <%= form_for @user do |f| %>
    <%= f.label "Access Level:" %>
    <%= f.select(:admin_level, [0, 1, 2]) %><br>

    <%= f.submit "Submit", :class => "btn btn-primary" %><br>
  <% end %>

<% end %>

app/views/users/index.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Edit User Account Access", :description => "Remember that 0 is the lowest access, and 2 is the maximum access."} do %>

  <div class="table-responsive">
    <table class="table table-hover">
        <thead class="">
          <tr>
              <th> User </th>
              <th> Admin Level </th>
              <th> Edit Access </th>
              <th> Delete User </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %> </td>
              <td><%= user.admin_level.to_s %></td>
              <td><%= button_to "Edit", edit_user_path(user), :class => "btn btn-primary", :method => :get %></td>
              <td><%= button_to "Delete", user_path(user), :class => "btn btn-primary", :method => :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

<% end %>

app/views/users/new.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Create a New User", :description => "Sign up/login in to keep track of your contacts & events"} do %>

  <%= render partial: "layouts/error_message", locals: {thing: @user} %>

  <%= form_for @user do |f| %>
    <%= f.label "Email" %>
    <%= f.text_field :email, class: "form-control" %><br>

    <%= f.label "Password" %>
    <%= f.text_field :password, class: "form-control"  %><br>

    <%= f.label "Access Code" %>
    <%= f.text_field :admin_level, class: "form-control"  %><br>

    <div class="row">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  <% end %>

    <%= button_to('Log in with Google!', '/auth/google_oauth2', class: "btn btn-primary") %>
    </div>
<% end %>