config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#index"

# creating model routes - note that user does not need show page
  resources :contacts
  resources :events
  resources :users, only: [:index, :edit, :create, :update, :destroy]

# creating nested routes for contact/:id/events & events/:id/contacts
  resources :contacts, only: [:index] do
    resources :events, only: [:index]
  end
  resources :events, only: [:index] do
    resources :contacts, only: [:index, :new, :create]
  end

# custom routes for login & logout
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

# custom routes for google auth
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/login')

# custom routes for newsletter and unsubscribers
  get '/newsletter', to: "contacts#newsletter"
  post '/newsletter', to: "contacts#newsletter_update"
  get '/unsubscribed', to: "contacts#unsubscribed"

# custom route for welcome night form
  get '/welcome', to: "contacts#welcome"
  post '/welcome', to: "contacts#welcome_create"

  get '/international_connect', to: "contacts#international_connect"
  post '/international_connect', to: "contacts#international_connect_create"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :contacts_events
  has_many :contacts, through: :contacts_events
  validates :name, presence: true
  validates :date, presence: true
  validates_numericality_of :staff_count, :only_integer => true
  validates_numericality_of :guest_count, :only_integer => true

  scope :access, -> (admin_level) { where('admin_level <= ?', admin_level) }

  def self.toggle_contact(params)
    if !!params[:event][:contacts]
      hash = {contact_id: params[:event][:contacts][:id], event_id: params[:id]}
      contact_event = ContactsEvent.find_by(hash)
      if !!contact_event then ContactsEvent.where(hash).each {|x| x.destroy } else ContactsEvent.create(hash) end
    end
  end

  def contacts_count
    self.contacts.count
  end

# to collect dates - bootstrap form params are not as clean as before
  def self.collect_date(event_params)
    Date.new event_params["date(1i)"].to_i, event_params["date(2i)"].to_i, event_params["date(3i)"].to_i
  end

  def admin_level=(admin_level)
    self[:admin_level] = admin_level
  end

  def admin_level
    self[:admin_level]
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

# before - check login, check resource access, load admin level
  before_action :redirect_if_no_login
  before_action :access_event, only: [:show, :edit, :update, :destroy]
  before_action :user_admin_level, only: [:index, :new, :create, :edit]

# events will be filtered based on whether it's nested under a contact or not
  def index
    if params[:contact_id]
      @contact = Contact.find(params[:contact_id])
      @events = @contact.events.order(date: :desc)
    else
      @events = Event.access(@user_admin_level).order(date: :desc)
    end
  end

  def new
    @event = Event.new
    @contacts = Contact.same_level(@user_admin_level).order(name: :asc)
    render :edit
  end

# add date, admin level, and contacts separately from .new method
  def create
    params["date"] = Event.collect_date(event_params) if params[:date]
    @event = Event.new(event_params)
    @event.admin_level = @user_admin_level
    if @event.save
      render json: @event, status: 201
    end
  end

  def show
    respond_to do |format|
      format.html {
        @contacts = @event.contacts
        render :show  }
      format.json { render json: @event, status: 200}
    end
  end

  def edit
    @contacts = Contact.same_level(@user_admin_level).order(name: :asc)
  end

# update contacts & date separately from .update method
  def update
    if !!params[:event][:name]
      params[:event][:date] = Event.collect_date(event_params)
      @event.update(event_params)
    end
    Event.toggle_contact(params)
    @event.save
    render json: @event, status: 201
  end

  def destroy
    @event.delete
    redirect_to events_path
  end

  private
  # permitted event parameters
  def event_params
    params.require(:event).permit(:name, :date, :guest_count, :staff_count, contacts: {}).select { |k, v| !v.nil? }
  end

  # finds events
  def find_event
    @event = Event.find(params[:id])
  end

  # uses find event to see if user has right access permission for event
  def access_event
    find_event
    if !has_access?(@event.try(:admin_level))
      flash.now[:alert] = "You cannot edit/view this event."
      redirect_to events_path
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper

  # to display event date in human readable format
  def display_date(event)
    event.date.strftime("%B %-d, %Y")
  end
end

app/views/events/_card_layout.html.erb
<div class="col-lg-4 justify-content-center">
    <div class="card card-stats">
      <div class="card-header card-header-icon">
        <div class="card-icon">
          <i class="material-icons"><%= icon_here %></i>
        </div>
      <h3 class="card-title"><%= header %></h3>
      <p class="card-category">
        <br>

        <%= yield %>

      </p>
    </div>
  </div>
</div>

app/views/events/_event_form.html.erb
<%= render partial: "layouts/error_message", locals: {thing: @event} %>
<%= render partial: "layouts/flash_message" %>
<%= csrf_meta_tag %>
<div id="form-wrapper">
<div class="row">
  <div class="col-md-12">
    <h3 class="card-title">Main Info</h3>
      <%= form_for @event, html: {class: 'main-details'} do |f| %>

          <%= f.label "Event Name", :class => "lb-lg" %>
          <%= f.text_field :name, :class => "form-control" %><br>

          <%= f.label "Event Date", :class => "lb-lg" %><br>
          <p>Reminder: Check the events homepage to ensure that today's event wasn't already created.</p>
          <%= f.date_select :date, {}, {class: "custom-select"} %><br><br>


          <%= f.label "Staff Count", :class => "lb-lg" %>
          <%= f.text_field :staff_count, :class => "form-control" %><br>

          <%= f.label "# Untracked Attendees", :class => "lb-lg" %>
          <%= f.text_field :guest_count, :class => "form-control" %><br>
    <div class="row justify-content-center">
            <%= f.submit "Submit/Lock Info", id: "submit", "data-id": @event.id, class: "btn btn-primary" %><br>
          <% end %>

            <% if !!@event.try(:id) %>
              <%= button_to "Delete Event", "#{event_path(@event)}", :class => "btn btn-danger", :method => :delete %>
            <% end %>
    </div>
    </div>
  </div>
</div>









<%= javascript_include_tag "events" %>

app/views/events/edit.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Edit an Event", :description => "Update an event's properties"} do %>
  <%= render partial: "event_form", locals: {event: @event} %>
<br>
  <div class="row" id="attendees-section">
    <div class="col-md-8">
      <%= form_for @event, html: {class: 'add-attendees'} do |f| %>
        <h3 class="card-title">Attendees</h3>
          Begin typing to find a new contact to add.<br>
         <%= f.fields_for :contacts do |ff| %>
           <%= ff.text_field :name, class: "form-control", list: "contacts_autocomplete" %>
           <datalist id="contacts_autocomplete">
           <% @contacts.each do |c| %>
             <option data-id="<%= c.id %>" value="<%= c.name %>"></option>
           <% end %>
           </datalist>
         <% end %>
         <a href="#" class="lookup-button"><i class="material-icons">info</i></a>
         <a href="#" class="add-button" data-id="<%= params[:id] %>"><i class="material-icons">add_circle</i></a><br>

         <div id="attendees">
        <% if @event.contacts.length > 0 %>
          <% @event.contacts.map do |c| %>
            <div id="<%= "small_button_" + c.id.to_s %>" class="btn btn-primary btn-sm"><%= c.name %>
            <a href="#" class="more-button" data-id="<%= c.id %>"><i class="material-icons inverse">info</i></a>
            <a href="#" class="remove-button" data-contact-id="<%= c.id %>" data-event-id="<%= params[:id] %>"><i class="material-icons inverse">remove_circle</i></a>
            </div>
          <% end %>
        <% end %>
        <br>
    </div>
    </div>
    <div id="info-container" class="col-md-4 justify-content-center">
      <h3 class="card-title">More Contact Info</h3>
        <div id="more-div">
          Drill down by selecting any info icon on the page
        </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/events/index.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => ("View Event for Contact #{params[:contact_id]}" if !!params[:contact_id]) || "View All Events", :description => "Coming soon: feature to sort by type of event"} do %>

  <div class="row justify-content-end">
      <%= link_to new_event_path, :class => "btn btn-primary" do %>
        Create New Event   <i class="material-icons">note_add</i>
      <% end %>
  </div>

  <div class="table-responsive">
    <table class="table table-hover">
        <thead class="">
          <tr>
              <th> Event Name </th>
              <th> Event Date </th>
              <th> Students </th>
              <th> # Untracked </th>
              <th> Staff </th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= link_to event.name, event_path(event) %> </td>
              <td><%= display_date event %></td>
              <td><%= link_to event.contacts_count, event_contacts_path(event) %></td>
              <td><%= event.guest_count %></td>
              <td><%= event.staff_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="row justify-content-center">
      <%= button_to "Create New Event", new_event_path , :class => "btn btn-primary", :method => :get %>
    </div>

<% end %>

app/views/events/new.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Create an Event", :description => "Create a new event to track data"} do %>
      <%= render partial: "event_form", locals: {event: @event} %>
<% end %>

app/views/events/show.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => (@event.name + " on " + display_date(@event)), :description => "Use the buttons below to change viewing options"} do %>

  <%= render :partial => "layouts/flash_message" %>

<div class="row justify-content-center center-this-div">
  <%= render :layout => 'events/card_layout', :locals => {header: "Event Info", icon_here: "info"} do %>
          <label>Name:</label> <%= @event.name %><br>
          <label>Date:</label> <%= display_date(@event) %><br>
          <label>Created On:</label> <%= @event.created_at.strftime("%B %-d, %Y") %><br>

  <% end %>
  <%= render :layout => 'events/card_layout', :locals => {header: "Head Counts", icon_here: "person"} do %>
          <label>Student Count:</label> <%= @event.contacts_count %><br>
          <label># Untracked:</label> <%= @event.guest_count %><br>
          <label>Staff Count:</label> <%= @event.staff_count %>

  <% end %>
  <div class="col-lg-4 justify-content-center">
      <%= link_to new_event_contact_path(@event), :class => "btn btn-primary btn-block" do %>
        Create Contact <i class="material-icons">person_add</i>
        <% end %>
      <%= link_to edit_event_path(@event), :class => "btn btn-primary btn-block" do %>
        Modify Event <i class="material-icons">edit</i>
        <% end %>
      <%= link_to new_event_path, :class => "btn btn-primary btn-block" do %>
        Create Event <i class="material-icons">library_add</i>
        <% end %>
        <br>
</div>
</div>

<div class="row">
<div class="col-lg-12">
  <div class="table-responsive">
    <table class="table table-hover">
        <thead class="">
          <tr>
              <th><%= "Name" %></th>
              <th><%= "Action" %></th>
              <th><%= "Staff" %></th>
              <th><%= "Email" %></th>
              <th><%= "Gender" %></th>
          </tr>
        </thead>
        <tbody>
            <% @contacts.each do |contact| %>
              <tr>
                <td>
                  <%= contact.name %>
                </td>
                <td>
                  <%= link_to edit_contact_path(contact) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                  <%= link_to contact_path(contact) do %>
                    <i class="material-icons">zoom_in</i>
                  <% end %>
                </td>
                <td><%= contact.user_name %></td>
                <td><%= contact.email %></td>
                <td><%= contact.gender %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
<% end %>