config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#index"

# creating model routes - note that user does not need show page
  resources :contacts
  resources :events
  resources :users, only: [:index, :edit, :create, :update, :destroy]

# creating nested routes for contact/:id/events & events/:id/contacts
  resources :contacts, only: [:index] do
    resources :events, only: [:index]
  end
  resources :events, only: [:index] do
    resources :contacts, only: [:index, :new, :create]
  end

# custom routes for login & logout
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

# custom routes for google auth
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/login')

# custom routes for newsletter and unsubscribers
  get '/newsletter', to: "contacts#newsletter"
  post '/newsletter', to: "contacts#newsletter_update"
  get '/unsubscribed', to: "contacts#unsubscribed"

# custom route for welcome night form
  get '/welcome', to: "contacts#welcome"
  post '/welcome', to: "contacts#welcome_create"

  get '/international_connect', to: "contacts#international_connect"
  post '/international_connect', to: "contacts#international_connect_create"
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :contacts_events
  has_many :events, through: :contacts_events

  validates :name, presence: true

  scope :active, -> { where('updated_at >= ?', Date.today - 3.month) }
  scope :same_level, -> (admin_level) { where('admin_level = ?', admin_level) }
  scope :newsletter_pending, -> (admin_level) { where("newsletter = ? AND email <> ? AND unsubscribed = ? AND admin_level <= ?", false, "", false, admin_level) }
  scope :unsubscribed, -> (admin_level) { where("unsubscribed = ? AND updated_at > ? AND admin_level <= ?", true, 1.month.ago, admin_level) }

  def self.update_newsletter_status(contacts)
    contacts.each do |contact|
      contact.newsletter = true
      contact.save
    end
  end

  def set_event(id, admin_level)
    if !id.empty?
      @event = Event.find_by(id: id)
      if (!!@event && (@event.admin_level <= admin_level)) then self.events << @event end
    end
  end

  def admin_level=(user)
    self[:admin_level] = user.admin_level
  end

  def admin_level
    self[:admin_level]
  end

  def user_name
    self.user.name if self.user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
# before actions - check logged in, check access resource, set admin level for forms
  before_action :redirect_if_no_login
  skip_before_action :redirect_if_no_login, only: [:welcome, :welcome_create, :international_connect, :international_connect_create]
  before_action :access_contact, only: [:show, :edit, :update, :destroy]
  before_action :user_admin_level, only: [:new, :edit, :create, :index]

# decision tree for different kinds of params and secure sql
  def index
    #binding.pry
    @contact = Contact.new
    @contacts = nil

    if !!params[:contact] && !!params[:contact][:name]
      @contacts = Contact.where(name: params[:contact][:name], admin_level: user_admin_level)
    elsif !!params[:contact] && !!params[:contact][:email]
      user = User.find_by(email: params[:contact][:email], admin_level: user_admin_level)
      @contacts = user.contacts if !!user
    elsif !!params[:unclaimed]
      @contacts = Contact.where(user_id: 22, admin_level: user_admin_level)
    elsif !!params[:recently_updated]
      @contacts = Contact.where("updated_at >= ? AND admin_level = ?", Date.today - 1.month, user_admin_level).order(updated_at: :desc)
    elsif params[:event_id]
      event = Event.where("id = ? AND admin_level = ?", params[:event_id], user_admin_level)
      @contacts = event.contacts.order(updated_at: :desc)
    elsif !!params[:all]
      @contacts = Contact.same_level(user_admin_level)
    end
    # render as json or html
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @contacts, status: 200}
    end
  end

  def new
    @event_id = params[:event_id]
    @contact = Contact.new
  end

# creates contact while associating contact with applicable events and user admin level
  def create
    @contact = Contact.new(contact_params.except(:user_id, :event_id))
    @contact.admin_level=(User.find(session[:user_id]))
    @contact.set_event(contact_params[:event_id], user_admin_level)
    @user = User.find_by(id: contact_params[:user_id])
    @contact.user = @user
    @event = Event.find_by(id: contact_params[:event_id])
    if @contact.save then nested_contact_redirect(@event, @contact) else render :new end
  end

  def show
    @events = @contact.events
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @contact, status: 200}
    end
  end

  def edit
  end

  def update
    @user = User.find_by(id: contact_params[:user_id])
    @contact.user = @user
    @contact.update(contact_params.except(:user_id, :event_id))
    if @contact.save then redirect_to contact_path(@contact) else render :edit end
  end

  def destroy
    @contact.delete
    redirect_to contacts_path
  end

  def newsletter
    @contacts = Contact.newsletter_pending(current_user.admin_level)
  end

  def newsletter_update
    if params[:newsletters]
      @contacts = Contact.newsletter_pending(current_user.admin_level)
      Contact.update_newsletter_status(@contacts)
    end
    redirect_to "/newsletter"
  end

  def unsubscribed
    @contacts = Contact.unsubscribed(current_user.admin_level)
  end

  def welcome
    @contact = Contact.new
    render template: 'contacts/welcome', layout: false
  end

  def welcome_create
    @contact = Contact.new(contact_params)
    @user = User.find(22)
    @contact.user = @user
    @contact.admin_level=(@user)
    @event = Event.find_or_create_by(name: "Large Group", admin_level: 1, created_at: Date.current, date: Date.current)
    if @contact.save
      @contact.events << @event
      redirect_to "/welcome", notice: "Thank you! Submit a new response below."
    else
      redirect_to "/welcome", notice: "Please try again. Make sure you save your name."
    end
  end

  def international_connect
    @contact = Contact.new
    render template: 'contacts/international_connect', layout: false
  end

  def international_connect_create
    @contact = Contact.new(contact_params)
    @user = User.find(22)
    @contact.user = @user
    @contact.admin_level=(@user)
    @event = Event.find_or_create_by(name: "International Connect", admin_level: 1, created_at: Date.current, date: Date.current)
    if @contact.save
      @contact.events << @event
      redirect_to "/international_connect", notice: "Thank you! Submit a new response below."
    else
      redirect_to "/international_connect", notice: "Please try again. Make sure you save your name."
    end
  end

  private
  # allowed contact parameters
  def contact_params
    params.require(:contact).permit(:name, :email, :gender, :phone_number, :school_status, :last_day, :messenger_id, :major, :country, :birthday, :unsubscribed, :newsletters, :source, :event_id, :user_id)
  end

# finds contact
  def find_contact
    @contact = Contact.find(params[:id])
  end

# runs find_contact & returns T or F with error depending on user access level
  def access_contact
    find_contact
    if !has_access?(@contact.admin_level)
      flash[:notice] = "You cannot edit/view this contact."
      redirect_to contacts_path
    end
  end

# chooses redirect based on whether contact is nested or not
  def nested_contact_redirect(event, contact)
    if !!event then redirect_to event_path(event) else redirect_to contact_path(contact) end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper

  # to display birthday in human readable format
  def birthday_human(contact)
    if contact.birthday
      contact.birthday.strftime("%B %-d")
    else
      nil
    end
  end

  # change button text depending on whether creating nested contact or normal contact
  def c_button_text(params)
    ("Create Contact For Event" if !!params[:event_id]) || "Create Contact"
  end

# change button link depending on whether creating nested contact or normal contact
  def c_button_link(params)
    ("/events/#{params[:event_id]}/contacts/new" if !!params[:event_id]) || new_contact_path
  end

# change header depending on which data set of contacts is selected
  def c_index_header(params)
    if params[:event_id]
      "View Contacts for Event #{params[:event_id]}"
    elsif params[:display_all]
      "View All Contacts"
    else
      "View My Contacts"
    end
  end

# helps newsletter team know where to add people to
  def event_source(contact)
    id = contact.contacts_events.minimum(:event_id)
    first_event = Event.find_by(id: id).try(:name)
    if !!first_event && !!first_event.match(/.*CSM.*/)
      "CSM WeChat"
    else
      "Newsletter"
    end
  end
end

app/views/contacts/_card_layout.html.erb
<div class="col-lg-4">
    <div class="card card-stats">
      <div class="card-header card-header-icon">
        <div class="card-icon">
          <i class="material-icons"><%= icon_here %></i>
        </div>
      <h3 class="card-title"><%= header %></h3>
      <p class="card-category">

        <%= yield %>

      </p>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Edit a Contact", :description => "Add as much information about the contact as you can"} do %>

  <%= render partial: "contact_form", locals: {contact: @contact} %>
  <%= button_to "Delete Contact", "#{contact_path(@contact)}", :class => "btn btn-danger", :method => :delete %>


<% end %>

app/views/contacts/index.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => ("View Contacts"), :description => "Use the buttons below to change viewing options"} do %>
  <%= render :partial => "layouts/flash_message" %>
<%= form_for @contact, :html => {:class => 'container-fluid'} do |f| %>
  <div class="row">
    <div class="col-md-4">
      <h3>Find By Name</h3>
        <div class="input-group">
              <%= f.text_field :name, class: "form-control", list: "contacts_autocomplete" %>
              <datalist id="contacts_autocomplete">
              <% Contact.same_level(@user_admin_level).each do |c| %>
                <option data-id="<%= c.id %>" value="<%= c.name %>"></option>
              <% end %>
              </datalist>
            <span class="input-group-btn">
            <%= link_to contacts_path, :id => "name", :class => "btn btn-primary btn-stubby" do %> <i class="material-icons">search</i> <% end %>
          </span>
        </div>
      </div>
      <div class="col-md-4">
        <h3>Find By Staff</h3>
        <div class="input-group">
            <%= f.text_field :email, class: "form-control", list: "staff_autocomplete" %>
            <datalist id="staff_autocomplete">
            <% User.same_level(@user_admin_level).each do |u| %>
              <option data-id="<%= u.id %>" value="<%= u.email %>"></option>
            <% end %>
            </datalist>
          <span class="input-group-btn">
            <%= link_to contacts_path, :id => "staff", :class => "btn btn-primary btn-stubby" do %> <i class="material-icons">search</i>  <% end %>
          </span>
        </div>
      <br></div>
<br>
    <div class="col-md-4">
        <%= link_to contacts_path, :id => "recently_updated", :class => "btn btn-primary btn-block" do %>
          <i class="material-icons">access_time</i> Recently Updated
        <% end %>
        <%= link_to contacts_path, :id => "unclaimed", :class => "btn btn-primary btn-block" do %>
          <i class="material-icons">help</i> Unclaimed
        <% end %>
        <%= link_to contacts_path, :id => "all", :class => "btn btn-primary btn-block" do %>
          <i class="material-icons">public</i> All Contacts
        <% end %>
        <%= link_to new_contact_path, :id => "create", :class => "btn btn-primary btn-block" do %>
          <i class="material-icons">person_add</i> New Contact
        <% end %>
      </div>
    </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h3> Listed Contacts </h3>
    <div class="table-responsive">
      <table class="table table-hover">
          <thead class="">
            <tr>
                <th><%= "Name" %></th>
                <th><%= "Action" %></th>
                <th><%= "Staff" %></th>
                <th><%= "Email" %></th>
                <th><%= "Gender" %></th>
            </tr>
          </thead>
          <tbody>
            <% if !!@contacts %>
              <% @contacts.each do |contact| %>
                <tr>
                  <td><%= contact.name %></td>
                  <td>
                    <%= link_to edit_contact_path(contact) do %>
                      <i class="material-icons">edit</i>
                    <% end %>
                    <%= link_to contact_path(contact) do %>
                      <i class="material-icons">zoom_in</i>
                    <% end %>
                  </td>
                  <td><%= contact.user_name %></td>
                  <td><%= contact.email %></td>
                  <td><%= contact.gender %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

<%= javascript_include_tag "contacts" %>

app/views/contacts/international_connect.html.erb
<!--
=========================================================
 Material Dashboard - v2.1.1
=========================================================

 Product Page: https://www.creative-tim.com/product/material-dashboard
 Copyright 2019 Creative Tim (https://www.creative-tim.com)
 Licensed under MIT (https://github.com/creativetimofficial/material-dashboard/blob/master/LICENSE.md)

 Theme coded by Creative Tim

=========================================================

 The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Welcome to International Connect</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "//code.jquery.com/jquery-3.3.1.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>
  <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Raleway" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
  <style>
    .wrapper {
      background-image: none !important; background-color:#F9F3E5;
    }
    body {
      background-color: #F9F3E5 !important;
      background-image: none !important;
    }
    .main-panel {
      position: absolute !important;
      margin-top: -10% !important;
      background-color: white !important;
      float: none !important;
      margin-left: 25% !important;
      margin-right: 25% !important;
      width: 50% !important;
    }
    .main-panel {
      background-image: none !important;
    }
    .main-panel>.content {
      margin-top: 0px !important;
      padding: 15px 30px 30px 30px !important;
    }
    h2 {
      font-family: 'Raleway', cursive !important;
      font-size: 2.3rem !important;
      text-align: center !important;
      margin-left: auto !important;
      margin-right: auto !important;
    }
    .lb-lg {
      font-family: 'Raleway', cursive !important;
      color: #3C4858 !important;
      font-size: 1.2rem !important;
      margin-top: 8px !important;
    }
    .lb-sm {
      font-family: 'Raleway', cursive !important;
      color: #3C4858 !important;
      font-size: .9rem !important;
    }
    .bottom {
      border-bottom: 1px solid #D2D2D2 !important;
      margin-bottom: 25px !important;
    }
    .row {
      margin: 20px auto !important;
    }
    .form-check.form-check-inline{
      left: 25px !important;
    }


    @media only screen and (max-width: 1030px) {
      .main-panel {
        margin-left: 10% !important;
        margin-right: 10% !important;
        width: 80% !important;
      }
      h2 {
        font-size: 1.9rem !important;
      }
    }
  </style>
</head>

  <body>
    <div class="wrapper">
        <img class="img-fluid mx-auto d-block" src="<%= asset_path 'pinned_globe.png' %>">
  <!-- Container Begins -->
      <div class="main-panel">

        <div class="content">
          <div class="container-fluid">
            <div class="row bottom">
              <h2>Welcome to International Connect!</h2>
            </div>
            <%= render partial: "layouts/error_message", locals: {thing: @contact} %>
            <%= render partial: "layouts/flash_message" %>
              <%= form_for(Contact.new, :url => international_connect_path, :html => { :method => "post" }) do |f| %>
                <%= f.label "Name", class: "lb-lg" %>
                <%= f.text_field :name, class: "form-control" %><br>

                <%= f.label "Email", class: "lb-lg" %>
                <%= f.text_field :email, class: "form-control"  %><br>

                <%= f.label "Gender", class: "lb-lg" %><br>
                <div class="form-check form-check-inline">
                  <%= f.label "gender_female", class: "form-check-label" do %>
                    <%= f.label "Female", class: "lb-sm" %>
                    <%= f.radio_button :gender, "Female", class: "form-check-input" %>
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  <% end %>
                </div>
              <div class="form-check form-check-inline">
                  <%= f.label "gender_male", class: "form-check-label" do %>
                    <%= f.label "Male", class: "lb-sm" %>
                    <%= f.radio_button :gender, "Male", class: "form-check-input" %>
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  <% end %>
                </div><br>

                <%= f.label "Academic Status", class: "lb-lg" %><br>
                <%= f.select :school_status, ["Exchange", "Freshmen", "Sophomore", "Junior", "Senior", "Masters", "PhD", "Post Doc", "Visiting Scholar", "Family", "Alumni"], {include_blank: true}, {class: "custom-select"} %><br><br>

                <%= f.label "Major", class: "lb-lg" %>
                <%= f.text_field :major, class: "form-control" %><br>

                <%= f.label "How did you hear about tonight?", class: "lb-lg" %>
                <%= f.text_field :source, class: "form-control" %><br>

                <%= f.label "Would you like to receive our newsletter?", class: "lb-lg" %><br>
                <div class="form-check form-check-inline">
                    <%= f.label "unsubscribed_false", class: "form-check-label" do %>
                      <%= f.label "false", "Yes", class: "lb-sm" %>
                      <%= f.radio_button :unsubscribed, false, :checked => true, :value => true, class: "form-check-input" %>
                      <span class="circle">
                        <span class="check"></span>
                      </span>
                    <% end %>
                  </div>
                  <div class="form-check form-check-inline">
                      <%= f.label "unsubscribed_true", class: "form-check-label" do %>
                        <%= f.label "true", "No", class: "lb-sm" %>
                        <%= f.radio_button :unsubscribed, true, :checked => false, :value => true, class: "form-check-input" %>
                        <span class="circle">
                          <span class="check"></span>
                        </span>
                      <% end %>
                    </div><br>


                <div class="row justify-content-center">
                  <%= f.submit "Submit", id: "submit", class: "btn btn-primary" %><br>
                </div>
              <% end %>
        </div><!-- end container-fluid -->
      </div><!-- end content -->
    </div><!-- end main panel -->
    </div><!-- end wrapper -->
  </body>
</html>

app/views/contacts/new.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => "Create A New Contact", :description => "Keep track of your contacts here"} do %>
  <%= render partial: "contact_form", locals: {contact: @contact} %>
<% end %>

app/views/contacts/show.html.erb
<%= render :layout => 'layouts/12_col_view', :locals => {:header => ("Contact Information for " + @contact.name), :description => "View contact info and attended events below"} do %>

<%= render :partial => "layouts/flash_message" %>

<div class="row justify-content-center center-this-div">
  <%= render :layout => 'contacts/card_layout', :locals => {header: "Basic Bio", icon_here: "face"} do %>
    <label>Name:</label> <%= @contact.name %><br>
    <label>Gender:</label> <%= @contact.gender || "N/A" %><br>
    <label>Staff:</label> <%= @contact.user_name || "N/A" %><br>
    <label>School Status:</label> <%= @contact.school_status %><br>
  <% end %>
  <%= render :layout => 'contacts/card_layout', :locals => {header: "Contact Info", icon_here: "info"} do %>
        <label>Phone #:</label> <%= @contact.phone_number || "N/A" %><br>
        <label>Messenger ID:</label> <%= @contact.messenger_id.presence || "N/A" %><br>
        <label>Email:</label> <%= @contact.email.presence || "N/A" %><br>
        <label>Unsubscribed:</label> <%= @contact.unsubscribed %><br>
  <% end %>
  <%= render :layout => 'contacts/card_layout', :locals => {header: "Other Facts", icon_here: "color_lens"} do %>
        <label>Major:</label> <%= @contact.major.presence || "N/A" %><br>
        <label>Home Country:</label> <%= @contact.country.presence || "N/A" %><br>
        <label>Birthday:</label> <%= birthday_human(@contact) || "N/A" %><br>
        <label>Last Day In Davis:</label> <%= @contact.last_day || "N/A" %><br>
  <% end %>
</div>
<div class="row justify-content-center">
    <%= link_to edit_contact_path(@contact), :class => "btn btn-primary" do %>
      Edit Contact <i class="material-icons">edit</i>
    <% end %>
    <%= link_to new_contact_path, :class => "btn btn-primary" do %>
      New Contact <i class="material-icons">library_add</i>
    <% end %>
    <%= link_to contacts_path, :class => "btn btn-primary" do %>
      All  Contacts  <i class="material-icons">public</i>
    <% end %>
</div>
<br>
<div class="col-md-12">
  <div class="table-responsive">
    <table class="table table-hover">
        <thead class="">
          <tr>
              <th> Event Name </th>
              <th> Event Date </th>
              <th> Action </th>
              <th> Students </th>
              <th> Guests </th>
              <th> Staff </th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.name %> </td>
              <td><%= display_date event %></td>
              <td>
                <%= link_to edit_event_path(event) do %>
                  <i class="material-icons">edit</i>
                <% end %>
                <%= link_to event_path(event) do %>
                  <i class="material-icons">zoom_in</i>
                <% end %>
              </td>
              <td><%= link_to event.contacts_count, event_contacts_path(event) %></td>
              <td><%= event.guest_count %></td>
              <td><%= event.staff_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/contacts/welcome.html.erb
<!--
=========================================================
 Material Dashboard - v2.1.1
=========================================================

 Product Page: https://www.creative-tim.com/product/material-dashboard
 Copyright 2019 Creative Tim (https://www.creative-tim.com)
 Licensed under MIT (https://github.com/creativetimofficial/material-dashboard/blob/master/LICENSE.md)

 Theme coded by Creative Tim

=========================================================

 The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

 <!DOCTYPE html>
<html lang="en">
<head>
  <title>International Graduate Student Ministry Newsletter Signup</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "//code.jquery.com/jquery-3.3.1.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>
  <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Raleway" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
  <style>
    .wrapper {
      background-image: none !important; background-color:#F9F3E5;
    }
    body {
      background-color: #F9F3E5 !important;
      background-image: none !important;
    }
    .main-panel {
      position: absolute !important;
      margin-top: -10% !important;
      background-color: white !important;
      float: none !important;
      margin-left: 25% !important;
      margin-right: 25% !important;
      width: 50% !important;
    }
    .main-panel {
      background-image: none !important;
    }
    .main-panel>.content {
      margin-top: 0px !important;
      padding: 20px !important;
    }
    h1 {
      font-family: 'Raleway', cursive !important;
      margin-top: 10px !important;
      margin-bottom: 0rem !important;
    }
    .lb-lg {
      font-family: 'Raleway', cursive !important;
      color: #3C4858 !important;
      font-size: 1.2rem !important;
      margin-top: 8px !important;
    }
    .lb-sm {
      font-family: 'Raleway', cursive !important;
      color: #3C4858 !important;
      font-size: .9rem !important;
    }
    .bottom {
      border-bottom: 1px solid #D2D2D2 !important;
      margin-bottom: 25px !important;
    }
    .row {
      margin: 20px auto !important;
    }
    .form-check.form-check-inline{
      left: 25px !important;
    }
    #logo {
      display: block;
      min-width: 60%;
      margin: 0px auto 15px auto;
    }
    .btn.btn-primary {
    background-color: #3c4858 !important;
  }
    @media only screen and (max-width: 1350px) {
        h1 {
          font-size: 2.5rem !important;
        }
      }


    @media only screen and (max-width: 1125px) and (min-width: 700px) {
      .main-panel {
        margin-left: 5% !important;
        margin-right: 5% !important;
        width: 90% !important;
      }
      h1 {
        font-size: 2.2rem !important;
      }
      lb-lg {
        font-size: 1.0rem !important;
      }
        #logo{max-width: 60%;}
    }

    @media only screen and (max-width: 700px) {
      .main-panel {
        margin-left: 5% !important;
        margin-right: 5% !important;
        width: 90% !important;
      }
      h1 {
        font-size: 2.2rem !important;
      }
      lb-lg {
        font-size: 1.0rem !important;
      }
    }

  </style>
</head>

  <body>
    <div class="wrapper">
        <img class="img-fluid mx-auto d-block" src="<%= asset_path 'artem-bali-570692-unsplash.jpg' %>">
  <!-- Container Begins -->
      <div class="main-panel">

        <div class="content">
          <div class="container-fluid">
            <div class="row bottom">
              <div class="col-lg-3 col-sm-4 align-self-center text-center"">
                <img class="img-fluid" id="logo" src="<%= image_path('b&w_logo.png') %>">
              </div>
              <div class="col-lg-9 col-sm-8">
                <h1>IGSM Newsletter</h1>
                <p class="lb-lg">
                  Sign up here to receive photos & event information
                  for IGSM (International Graduate Student Ministry) Davis!</p>
              </div>
            </div>
            <%= render partial: "layouts/error_message", locals: {thing: @contact} %>
            <%= render partial: "layouts/flash_message" %>
              <%= form_for(Contact.new, :url => welcome_path, :html => { :method => "post" }) do |f| %>
                <%= f.label "Name", class: "lb-lg" %>
                <%= f.text_field :name, class: "form-control" %><br>

                <%= f.label "Email", class: "lb-lg" %>
                <%= f.text_field :email, class: "form-control"  %><br>

                <%= f.label "Gender", class: "lb-lg" %><br>
                <div class="form-check form-check-inline">
                  <%= f.label "gender_female", class: "form-check-label" do %>
                    <%= f.label "Female", class: "lb-sm" %>
                    <%= f.radio_button :gender, "Female", class: "form-check-input" %>
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  <% end %>
                </div>
              <div class="form-check form-check-inline">
                  <%= f.label "gender_male", class: "form-check-label" do %>
                    <%= f.label "Male", class: "lb-sm" %>
                    <%= f.radio_button :gender, "Male", class: "form-check-input" %>
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  <% end %>
                </div><br>

                <%= f.label "Phone Number", class: "lb-lg" %>
                <%= f.text_field :phone_number, class: "form-control" %><br>

                <%= f.label "Academic Status", class: "lb-lg" %><br>
                <%= f.select :school_status, ["Exchange", "Freshmen", "Sophomore", "Junior", "Senior", "Masters", "PhD", "Post Doc", "Visiting Scholar", "Family", "Alumni"], {include_blank: true}, {class: "custom-select"} %><br><br>

                <%= f.label "Major", class: "lb-lg" %>
                <%= f.text_field :major, class: "form-control" %><br>

                <%= f.label "How did you hear about us?", class: "lb-lg" %>
                <%= f.text_field :source, class: "form-control" %><br>

                <div class="row justify-content-center">
                  <%= f.submit "Submit", id: "submit", class: "btn btn-primary" %><br>
                </div>
              <% end %>
        </div><!-- end container-fluid -->
      </div><!-- end content -->
    </div><!-- end main panel -->
    </div><!-- end wrapper -->
  </body>
</html>